#!/usr/bin/env bash
# Script that displays information about subdomains.

DOMAIN=$1
SUB_DOMAINS=('www' 'lb-01' 'web-01' 'web-02')

custom_dig () {
    if [[ $1 =~ [a-z] ]]; then
        if [[ $2 =~ [a-z] ]]; then
            SUB_DOMAINS=("$2")
        fi
        for SUB_DOMAIN in "${SUB_DOMAINS[@]}"; do
            ANSWERLINE=$(dig "$SUB_DOMAIN"".""$DOMAIN" | grep -A1 'ANSWER SECTION:' | tail -n1 )
            RECORD_TYPE=$(echo "$ANSWERLINE" | awk '{print $4}')
            DESTINATION=$(echo "$ANSWERLINE" | awk '{print $5}')
            ANSWER="The subdomain $SUB_DOMAIN is a $RECORD_TYPE record and points to $DESTINATION"
            awk -v ANSWER="$ANSWER" 'BEGIN {print ANSWER}'
        done
    fi
}
custom_dig "$@"
