#!/usr/bin/env bash
# Script that setup a nginx web server on our server.

apt update -y && apt upgrade -y
apt install nginx -y

echo "Holberton School" >/var/www/html/index.nginx-debian.html

service nginx restart