#!/usr/bin/env bash
# Script that setup a nginx web server on our server + redirection.

apt update -y && apt upgrade -y
apt install nginx -y

# Index page
echo "Holberton School" >/var/www/html/index.nginx-debian.html

# Redirect to fabulous Rick Astley page
sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
