#!/usr/bin/env bash
# This script is doing a lot of things.

echo $$ >/var/run/holbertonscript.pid

trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm -f /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm -f /var/run/holbertonscript.pid; exit" SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
