#!/usr/bin/env bash
# This script is displaying "To infinity and beyond" indefinitely.
# Cannot be terminated.

trap "echo I am invincible!!!" SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
