#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.
i=0
while [ $i -lt 10 ]
    do
	((i++))
	echo "Holberton School" 
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
    done
