#!/usr/bin/env bash
# This script loops 10 times, displays "bad luck" for the 4th iteration,
# "good luck" for the 8th iteration and "Holberton School" for other iteration.

i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
