#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file.
filename="holbertonschool"
if [[ -e $filename ]]; then
	echo "$filename file exists"
	if [[ ! -s  $filename ]] && [[ -f $filename ]]; then
		echo "$filename file is empty"
	else
		echo "$filename file is not empty"
	fi
	if [[ -f $filename ]]; then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
