#!/usr/bin/env bash
# A script that installs apache and changes the home page output to "Hello Holberton".
apt-get install apache2 -y
echo "Hello Holberton" > /var/www/html/index.html 
echo "ServerName localhost" >> /etc/apache2/apache2.conf
/etc/init.d/apache2 start