#!/usr/bin/env bash
# Configures the container to run nginx as nginx user.

sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod -R 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
